apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nodeExporter-daemonset.yaml       
- nodeExporter-serviceAccount.yaml
- nodeExporter-clusterRoleBinding.yaml  
- nodeExporter-networkPolicy.yaml   
- nodeExporter-clusterRole.yaml
- nodeExporter-service.yaml
