apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./prometheusOperator-clusterRole.yaml
- ./prometheusOperator-clusterRoleBinding.yaml
- ./prometheusOperator-deployment.yaml
- ./prometheusOperator-networkPolicy.yaml
- ./prometheusOperator-service.yaml
- ./prometheusOperator-serviceAccount.yaml